### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by h8suga** [Mattiwatti/EfiGuard#37]
Its possible on old BIOS not UEFI?
my system dump:
```
SystemBootEnvironmentInformation:
        - BootIdentifier: {13299921-eaa4-11eb-9b90-d99f30e81197}
        - FirmwareType: BIOS
        - BootFlags: 0x1

SystemModuleInformation:
        - Kernel: ntoskrnl.exe (\SystemRoot\system32\ntoskrnl.exe)

SystemCodeIntegrityInformation:
        - IntegrityOptions: 0x0001

SystemKernelDebuggerInformation:
        - KernelDebuggerEnabled: 0
        - KernelDebuggerNotPresent: 1

SystemKernelDebuggerInformationEx:
        - DebuggerAllowed: 0
        - DebuggerEnabled: 0
        - DebuggerPresent: 0

SharedUserData->KdDebuggerEnabled: 0x00

SystemKernelDebuggerFlags: 0x00

SystemCodeIntegrityPolicyInformation:
        - Options: 0x40000000
        - HVCIOptions: 0x0000
```
