### ISSUE TITLE
error C0000002

### ISSUE THREAD

**Issue by Rikudouu** [Mattiwatti/EfiGuard#4]
I'm on Windows 1809 (soon 1903), and I get this error when trying any command other than -i

```
Failure: NtSetSystemEnvironmentValueEx error C0000002
AdjustCiOptions failed: C0000002
```

Full error with -d:
```
Disabling DSE...
CI!g_CiOptions at 0xFFFFF80514541D18.
Failure: NtSetSystemEnvironmentValueEx error C0000002
AdjustCiOptions failed: C0000002
```

-i output (after booting from the loader):
```
SystemBootEnvironmentInformation:
        - BootIdentifier: {c57e01ab-e8ac-11e8-9c47-c18f143fd988}
        - FirmwareType: BIOS
        - BootFlags: 0x0

SystemModuleInformation:
        - Kernel: ntoskrnl.exe (\SystemRoot\system32\ntoskrnl.exe)

SystemCodeIntegrityInformation:
        - IntegrityOptions: 0x0001

SystemKernelDebuggerInformation:
        - KernelDebuggerEnabled: 0
        - KernelDebuggerNotPresent: 1

SystemKernelDebuggerInformationEx:
        - DebuggerAllowed: 0
        - DebuggerEnabled: 0
        - DebuggerPresent: 0

SharedUserData->KdDebuggerEnabled: 0x00

SystemKernelDebuggerFlags: 0x00

SystemCodeIntegrityPolicyInformation:
        - Options: 0x40000000
        - HVCIOptions: 0x0000
```

I also pulled from master and compiled the EfiDSEFix but the same issue occurs.
