### ISSUE TITLE
Win11 21H2 BSOD on ''EfiDSEFix.exe -d'' Command

### ISSUE THREAD

**Issue by spIoopy** [Mattiwatti/EfiGuard#59]
## BlueScreenView

![image](https://user-images.githubusercontent.com/79509425/177531643-08d6b4ba-ba4f-44ff-b3b2-82a71f5e141c.png)

## Event Viewer

![image](https://user-images.githubusercontent.com/79509425/177531709-05a426ed-56c7-4636-9bae-0b8ef3825ab3.png)

`The computer has rebooted from a bugcheck.  The bugcheck was: 0x0000003b (0x00000000c0000005, 0xfffff8038062fd80, 0xfffff50d3b6f3cc0, 0x0000000000000000). A dump was saved in: C:\WINDOWS\MEMORY.DMP. Report Id: 49033993-ef6d-4d11-ba1a-d2dbbf2c7a86.`

![image](https://user-images.githubusercontent.com/79509425/177531813-9576e9ae-06c3-4844-9774-602c74dd97b8.png)

## BSOD

SYSTEM_SERVICE_EXCEPTION

0x00000000C0000005
0xFFFFF80264FAFD80
0xFFFFFD831774ECC0
0x0000000000000000

## Extra Info

First time using, tried the command 5 times, still the same thing!

**Comment by Mattiwatti** [comment]
Sorry for the delay. Since this is Windows 11: do you have Hyper-V enabled? If yes, you should disable it, see #57. If no, please upload the crash dump file here so I can take a look at it. Thanks.

**Comment by goonette** [comment]
you need to make sure Hyper-V is disabled in windows and that any virtualisation is disabled in your bios

**Comment by cr4shboy** [comment]
Hey @Mattiwatti,

Same issue on Win11 22H2.
Pretty sure Hyper-V is disabled (checked, rebooted). Seems like boot-up process goes well, but when trying to use `EfiDSEFix.exe -d` after 2sec. it goes BSOD `Cl.dll - ATTEMPTED_WRITE_TO_READONLY_MEMORY`

Memory integrity, real time AV protection disabled.

![image](https://user-images.githubusercontent.com/28809511/222728544-76c7c122-7204-46c6-b889-5dd6afbbc45c.png)
[030323-5656-01.zip](https://github.com/Mattiwatti/EfiGuard/files/10882276/030323-5656-01.zip)

**Comment by Mattiwatti** [comment]
Thanks for the crash dump. Can you also post the output of `EfiDSEFix.exe -i` please?

**Comment by cr4shboy** [comment]
@Mattiwatti Of course.

```
SystemBootEnvironmentInformation:
        - BootIdentifier: {da4cf360-952e-11ed-ab5b-bfeced838031}
        - FirmwareType: UEFI
        - BootFlags: 0x0

SystemModuleInformation:
        - Kernel: ntoskrnl.exe (\SystemRoot\system32\ntoskrnl.exe)

SystemCodeIntegrityInformation:
        - IntegrityOptions: 0x2001

SystemKernelDebuggerInformation:
        - KernelDebuggerEnabled: 0
        - KernelDebuggerNotPresent: 1

SystemKernelDebuggerInformationEx:
        - DebuggerAllowed: 0
        - DebuggerEnabled: 0
        - DebuggerPresent: 0

SharedUserData->KdDebuggerEnabled: 0x00

SystemKernelDebuggerFlags: 0x00

SystemCodeIntegrityPolicyInformation:
        - Options: 0x40000081
        - HVCIOptions: 0x0000
```
